### ISSUE TITLE
Can i get code from GIT and run a test in loadrunner cloud using the plugin

### ISSUE THREAD

**Issue by SenthilkumarRasan** [jenkinsci/loadrunner-cloud-plugin#113]
### What feature do you want to see added?

Option to get updated code from Github repo and create/update test in LRC and execute the test

**Comment by weisun10** [comment]
Can you please share more details about the scenario?

If you want to create/update tests in LRC to use the codes from your Git repo, one option:
1.  use external plugin or git CLIs to get latest codes from Git repo
2.  invoke LRC Public APIs to create / update tests
3.  pass the newly created or updated test ID to the Jenkins plugin via parameter

**Comment by weisun10** [comment]
no response for a long time, close
